#!/usr/bin/env python3
import sys
import asyncio
import argparse

# The path to import libraries need to be included
sys.path.insert(1, '/Users/marshallamey/bin/sysadmintools/lib')
from Okta import Okta


## Parse command arguments
parser = argparse.ArgumentParser()
parser.add_argument('-c', '--company', 
    help='provide name of the company domain used in Okta',  
    metavar=''
)
args = parser.parse_args()
if not args.company:
    print('You must include the company domain as an argument. Use --help for more information')
    quit()

OKTA = Okta(args.company)
loop = asyncio.get_event_loop()
loop.run_until_complete(OKTA.getUsers())
